### ISSUE TITLE
回调接口验证失败，好像是没有实现验证的方法

### ISSUE THREAD

**Issue by leochen-g** [wechaty/puppet-walnut#41]
说明： 已经配置好所有账户信息后，回调地址也已经实现内网穿透，但是在回调接口鉴权的时候提示验证失败
<img width="305" alt="image" src="https://user-images.githubusercontent.com/20028566/166203837-402e3856-f124-4c8a-944a-72ab1a4d87d0.png">

原因排查：根据5G接口文档说明，5G业务平台会在首次接入的时候进行鉴权，如下图
<img width="521" alt="image" src="https://user-images.githubusercontent.com/20028566/166204007-dc6f533d-39bc-4fea-98e3-b7e5f90fba1f.png">

但是我发现server中的router地址为`/sms/notifyPath`，并且方法里只有log，并没有任何返回，使鉴权的时候返回的状态码为404，导致无法成功鉴权

<img width="1638" alt="image" src="https://user-images.githubusercontent.com/20028566/166204145-c695bcc8-3536-4d31-8834-582704327f48.png">
<img width="1600" alt="image" src="https://user-images.githubusercontent.com/20028566/166204259-1d14209f-b27c-4337-b6e7-c1795a0260f7.png">

**Comment by fabian4** [comment]
@leochen-g 
It has been fix by https://github.com/wechaty/puppet-walnut/pull/42
You can try it on and I hope it works fine.
