### ISSUE TITLE
Use environment variables to config the puppet

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-walnut#7]
for example, `WECHATY_PUPPET_WALNUT_APPID`.

> We should always use `WECHATY_PUPPET_WALNUT_` as the prefix.

**Comment by huan** [comment]
Any information for the closing?

Have we started following the environment variable naming convention now?

**Comment by fabian4** [comment]
Here is how I use the environment variables
~~~ts
  PuppetWalnut.sipId = options?.sipId || process.env['WECHATY_PUPPET_WALNUT_SIPID'] || ''
  PuppetWalnut.appId = options?.appId || process.env['WECHATY_PUPPET_WALNUT_APPID'] || ''
  PuppetWalnut.appKey = options?.appKey || process.env['WECHATY_PUPPET_WALNUT_APPKEY'] || ''
  if (!PuppetWalnut.sipId || !PuppetWalnut.appId || !PuppetWalnut.appKey) {
    throw new Error('Set your Environment variables')
  }
~~~

**Comment by huan** [comment]
Great to know that!

Could you please add them to README so that other developers can read docs to learn them?

**Comment by fabian4** [comment]
It is already in the RAEDME file
https://github.com/wechaty/puppet-walnut/blob/f3b9c64d1308b1d3e1f1c8bf9f0902f2062562b8/README.md?plain=1#L18-L23

**Comment by huan** [comment]
That's awesome, thank you very much for the information l.

It would be great if you can link the commit to the related issue in the future so that every thing can be clear to our community.
