### ISSUE TITLE
Design a `PuppetWalnutOptions` interface to accept puppet options

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-walnut#8]
We should be able to configure the puppet either by setting the environment variables, or by setting a `options` and pass it to `new PuppetWalnut(options)`.

**Comment by fabian4** [comment]
It has been implemented already:
~~~ts
export type PuppetWalnutOptions = PUPPET.PuppetOptions & {
  sipId?: string,
  appId?: string,
  appKey?: string,
}
~~~

**Comment by fabian4** [comment]
here's the code https://github.com/wechaty/puppet-walnut/blob/f3b9c64d1308b1d3e1f1c8bf9f0902f2062562b8/src/puppet-walnut.ts#L32-L36

**Comment by huan** [comment]
OK, thank you very much for linking that information together, it will be useful in the future and for easy understanding to other developers in the community!
