### ISSUE TITLE
Enable update `accessToken` within the Puppet (Please refer to Wechaty Puppet Official Account)

### ISSUE THREAD

**Issue by zrn-fight** [wechaty/puppet-walnut#9]
After adding the puppet-walnut.spec.ts test file, CI cannot pass.The job running on runner Hosted Agent will exceede the maximum execution time of 360 minutes.

**Comment by huan** [comment]
REMEMBER: NEVER DELETE UNIT TEST FILES. FIX THEM INSTEAD.

**Comment by fabian4** [comment]
It is done with https://github.com/wechaty/puppet-walnut/pull/43
